version: '3.9'

services:
  ebay-chat1:
    build: .
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=CloneEbayDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - appnet
    ports:
      - "127.0.0.1:5001:8080"
    volumes:
      - dpkeys:/keys

  ebay-chat2:
    build: .
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=CloneEbayDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - appnet
    ports:
      - "127.0.0.1:5002:8080"
    volumes:
      - dpkeys:/keys

  ebay-chat3:
    build: .
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=CloneEbayDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - appnet
    ports:
      - "127.0.0.1:5003:8080"
    volumes:
      - dpkeys:/keys

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-ebaychat
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "127.0.0.1:1433:1433"
    networks:
      - appnet
    volumes:
      - dbdata:/var/opt/mssql  # persist database

networks:
  appnet:

volumes:
  dpkeys:  # shared Data Protection keys
  dbdata:  # persist SQL Server data
