version: '3.9'

services:
  ebay-chat1:
    build: 
      context: .
      target: runtime
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=CloneEbayDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
      - redis
    networks:
      - appnet
    ports:
      - "127.0.0.1:5001:8080"
    volumes:
      - dpkeys:/keys

  ebay-chat2:
    build: 
      context: .
      target: runtime
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=CloneEbayDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
      - redis
    networks:
      - appnet
    ports:
      - "127.0.0.1:5002:8080"
    volumes:
      - dpkeys:/keys

  ebay-chat3:
    build: 
      context: .
      target: runtime
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=CloneEbayDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
      - redis
    networks:
      - appnet
    ports:
      - "127.0.0.1:5003:8080"
    volumes:
      - dpkeys:/keys

  migrate:
    build:
      context: .
      target: migrate
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=CloneEbayDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    networks:
      - appnet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-ebaychat
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "127.0.0.1:1433:1433"
    networks:
      - appnet
    volumes:
      - dbdata:/var/opt/mssql

  redis:
    image: redis:7-alpine
    container_name: redis-ebaychat
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - appnet

networks:
  appnet:

volumes:
  dpkeys:
  dbdata:
